/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ImpactNFTInterface extends Interface {
    getFunction(nameOrSignature: "records" | "registerImpact" | "totalRecords"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'records', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerImpact', values: [string, string]): string;
encodeFunctionData(functionFragment: 'totalRecords', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'records', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerImpact', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRecords', data: BytesLike): Result;
  }

  

  export interface ImpactNFT extends BaseContract {
    
    connect(runner?: ContractRunner | null): ImpactNFT;
    waitForDeployment(): Promise<this>;

    interface: ImpactNFTInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    records: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint] & {action: string, participant: string, timestamp: bigint }],
      'view'
    >
    

    
    registerImpact: TypedContractMethod<
      [_action: string, _participant: string, ],
      [void],
      'nonpayable'
    >
    

    
    totalRecords: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'records'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint] & {action: string, participant: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'registerImpact'): TypedContractMethod<
      [_action: string, _participant: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalRecords'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }